remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: "Didattica Tntegrativa 2023"
description: "Didattica integrativa per il corso Analisi Dati in Psicologia dello Sviluppo 2022-2023"
show_downloads: ["true"]
